spring.application.name=com.minhtung.hackathon
app.base-url=https://umbilical-daisy-submersed.ngrok-free.dev

# Database Configuration ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/swp391
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=false

# JPA/Hibernate Configuration ============================================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS Configuration ============================================
spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:8080
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Cấu hình JWT ==================================================
security.jwt.secret-key=ChuyenChuoiNayThanhKeyCoDoDaiTren32KyTuDeDamBaoAnToanNheBanOi123456
security.jwt.expiration-time=60000

# ===============================================================
# CẤU HÌNH JAVA MAIL SENDER (GMAIL) - FIX TRIỆT ĐỂ CHO JAVA 21
# ===============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thainguyenthanh504@gmail.com
spring.mail.password=hyuccugnyrnkxeri




cloudinary.cloud-name=daak9kxkx
cloudinary.-apikey=224951116799529
cloudinary.api-secret=9CHKg6Qicoqb-GxB0K2jFG2QRq8





idanalyzer.api-key=idk_Tz7roOD45WXy5KLmPwQ8SeYEcPJFXSRD06FKnNVN
idanalyzer.scan-url=https://api2.idanalyzer.com/scan
idanalyzer.face-url=https://api2.idanalyzer.com/face
idanalyzer.profile=security_medium
kyc.face-match-threshold=40
kyc.face-match-max-attempts=3

submission.demo.max-size=20MB
submission.document.max-size=10MB


# Cấu hình Spring Boot cho phép nhận file lớn
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=210MB

# Bổ sung đầy đủ các thuộc tính bảo mật TLS bắt buộc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000