# =========================
# App
# =========================
spring.application.name=com.minhtung.hackathon
app.base-url=https://onlooker-crux-shock.ngrok-free.dev

# =========================
# Database (PostgreSQL)
# =========================

#spring.datasource.url=jdbc:postgresql://localhost:5432/hackathon_db
#spring.datasource.username=hackathon_user
#spring.datasource.password=123456

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tắt Flyway nếu project không có migration (hoặc để tránh tạo flyway_schema_history)
spring.flyway.enabled=false

# =========================
# CORS
# =========================
spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:8080
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# =========================
# JWT
# =========================
security.jwt.secret-key=your_jwt_secret_key_here
security.jwt.expiration-time=60000

# =========================
# Mail (có thể để trống nếu chưa dùng)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=scarletdiamond912@gmail.com
spring.mail.password=ppjfbakrgvywmkfl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================
# Cloudinary Configuration
# =========================
cloudinary.cloud-name=df5ismxf9
cloudinary.api-key=313421379524385
cloudinary.api-secret=4nieHIdN_OrpP-EQsUhDx_BP-lA

# =========================
# KYC / FPT.AI Configuration
# =========================
fpt.ai.api-key=78349aDSxKpDAE96oOH5oDIVq7GRMyDt
fpt.ai.id-recognition-url=https://api.fpt.ai/vision/idr/vnm
fpt.ai.face-match-url=https://api.fpt.ai/dmp/checkface/v1/
idanalyzer.api-key=idk_Tz7roOD45WXy5KLmPwQ8SeYEcPJFXSRD06FKnNVN
idanalyzer.scan-url=https://api2.idanalyzer.com/scan
idanalyzer.face-url=https://api2.idanalyzer.com/face
idanalyzer.profile=security_medium
kyc.face-match-threshold=60
kyc.face-match-max-attempts=3

submission.demo.max-size=100MB
submission.document.max-size=20MB
